CREATE TABLE sequence(
	id VARCHAR(50) NOT NULL PRIMARY KEY,
	type VARCHAR(30) NOT NULL COMMENT '序列类型',
	increment TINYINT(3) NULL COMMENT '递增序列值',
	start_value BIGINT(20) NULL COMMENT '开始值',
	min_value BIGINT(20) NULL COMMENT '最小值',
	max_value BIGINT(20) NULL COMMENT '最大值',
	current_value BIGINT(20) NOT NULL COMMENT '当前值',
	create_by VARCHAR(50) NOT NULL COMMENT '创建人',
	create_date DATETIME NOT NULL COMMENT '创建时间',
	update_by VARCHAR(50) NULL COMMENT '更新人',
	update_date DATETIME NULL COMMENT '更新时间',
	remarks VARCHAR(300) NULL COMMENT '备注',
	del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标识(0：正常，1:删除)',
	version SMALLINT(6) NOT NULL DEFAULT 0 COMMENT '版本号'
);


DELIMITER $$
DROP FUNCTION IF EXISTS getSeqByType$$
CREATE FUNCTION getSeqByType(type VARCHAR(30)) RETURNS BIGINT(20)
BEGIN
	DECLARE TMP_CURRENT BIGINT(20);
	DECLARE TMP_START BIGINT(20);
	DECLARE TMP_INCREMENT BIGINT(3);
	
	SELECT `start_value`
	FROM `sequence`
	WHERE type = TYPE INTO TMP_START;
		
	SELECT `current_value`
	FROM `sequence`
	WHERE type = TYPE INTO TMP_CURRENT;
	
	SELECT INCREMENT FROM sequence WHERE type = type INTO TMP_INCREMENT;
	
	IF (TMP_START > TMP_CURRENT) THEN 
		SET TMP_CURRENT = TMP_START;
	ELSE 
		SET TMP_CURRENT = (TMP_CURRENT + TMP_INCREMENT);
	END IF;
	
	UPDATE sequence SET `current_value` = TMP_CURRENT WHERE type = type;
	RETURN TMP_CURRENT;
END $$

DELIMITER ;
