ALTER TABLE contact
MODIFY COLUMN tel varchar(50) NULL DEFAULT NULL COMMENT '座机号';
ALTER TABLE contact
MODIFY COLUMN email varchar(50) NULL DEFAULT NULL COMMENT '电子邮箱';
ALTER TABLE contact
MODIFY COLUMN phone varchar(50) NULL DEFAULT NULL COMMENT '手机号码';
ALTER TABLE contact
MODIFY COLUMN mt_province_cd varchar(50) NULL DEFAULT NULL COMMENT '省份代码';
ALTER TABLE contact
MODIFY COLUMN mt_city_cd varchar(50) NULL DEFAULT NULL COMMENT '城市代码';
ALTER TABLE contact
MODIFY COLUMN mt_county_cd varchar(50) NULL DEFAULT NULL COMMENT '区县代码';
ALTER TABLE contact
MODIFY COLUMN address varchar(150) NULL DEFAULT NULL COMMENT '详细地址';